name: CI Workflow

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build: # Mainly for lint & typecheck
    strategy:
      fail-fast: false  # See all OS results 
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }} # Run job instances across the multiple OS in parallel

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm  # Built-in dependency caching for npm
        
      # Clean install dependencies from package-lock.json
        # Automatically removes existing node_modules beforehand
        # Better for automated environments than npm install
      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

  test: # For unit tests
    strategy:
      fail-fast: false  # See all OS results 
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }} # Run job instances across the multiple OS in parallel

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm  # Built-in dependency caching for npm

      # Clean install dependencies from package-lock.json
      - name: Install dependencies
        run: npm ci
  
      - name: Test
        run: npm test # Test coverage >=90 is not enforced yet